### ISSUE TITLE
Error when deploying app to knative

### ISSUE THREAD

**Issue by daisy-ycguo** [serverless-components/knative-serving#3]
Error message when `serverless deploy` to knative instance using the sample application:

```
  TypeError: Cannot read property 'code' of undefined
      at KnativeServing.default (/Users/Daisy/workspace/serverless/my-service/node_modules/@serverless/knative-serving/serverless.js:25:34)
```

The commands I run
```
npm install serverless --global
serverless create --template knative-docker --path my-service
cd my-service/
npm install
serverless deploy
```

**Comment by mjschmidt** [comment]
ran this with the debug turned on and got the full error message:
```
 TypeError: Cannot read property '0' of undefined
      at KnativeServing.getIstioIngressIp (/home/mjschm3/serverless/my-service/node_modules/@serverless/knative-serving/serverless.js:78:48)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at KnativeServing.default (/home/mjschm3/serverless/my-service/node_modules/@serverless/knative-serving/serverless.js:37:16)
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:489:22)
      at /snapshot/serverless/lib/classes/PluginManager.js:524:24
  From previous event:
      at PluginManager.run (/snapshot/serverless/lib/classes/PluginManager.js:524:8)
      at /snapshot/serverless/lib/Serverless.js:131:33
  From previous event:
      at Serverless.run (/snapshot/serverless/lib/Serverless.js:118:74)
      at /snapshot/serverless/bin/serverless.js:80:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:80:4)
      at Module._compile (pkg/prelude/bootstrap.js:1320:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
      at internal/main/run_main_module.js:18:47
```

**Comment by mjschmidt** [comment]
Looking at the github README.md vs the docs found [here](https://www.serverless.com/framework/docs/getting-started/)

It looks like the .env file is not being created when the serverless template command is run. tried to create the .env file manually and update it with the required information, but that did not seem to work either. Not sure what to look into next. Let me know :)

**Comment by eddiewang** [comment]
Hi @daisy-ycguo - were you ever able to resolve this issue?

**Comment by skynetcmg47** [comment]
> Looking at the github README.md vs the docs found [here](https://www.serverless.com/framework/docs/getting-started/)
> 
> It looks like the .env file is not being created when the serverless template command is run. tried to create the .env file manually and update it with the required information, but that did not seem to work either. Not sure what to look into next. Let me know :)

hi @mjschmidt, I ran into the same problem, were u able to resolve this ?

**Comment by mjschmidt** [comment]
No, we ultimately made a decision to just use knative as it served our needs. It was going to be just as much work to try to use the serverless/serverless libs to provide the level of abstraction as it was to just take code and launch it to either lambda or knative. We are checking back periodically to see if we can leverage the serverless/serverless libraries, but so far we have a low level of confidence :)
